name: CodeReview

on:
  pull_request_review:
    types: [ submitted ]
jobs:
  sendReview:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://c5770934-778c-4432-b5c9-31aa5da57394.mock.pstmn.io/v1/codeReview'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"repoName": "${{github.repository}}", "repoOwner": "${{github.repository_owner}}", "pull_number":"${{github.ref}}"}'
